routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login')->with('errorsLogin','');
})->name('screen');

Route::get('/login', function () {
    return view('auth.login')->with('errorsLogin','');
})->name('login');

Route::get('/reset', function () {
    return view('auth.passwords.email');
})->name('password.request');


Route::get('/home', 'HomeController@index')->name('home');
Route::post('/change-password', 'UserController@changePassword')->name('change.password');

Route::get('/cities', 'RestController@cities');
Route::get('/providences', 'RestController@providences');

Route::post('/cities', 'RestController@saveCities');
Route::post('/providences', 'RestController@saveProvidences');

Route::get('/directors', 'RestController@directors');
Route::get('/selected/{club}','RestController@selected')->name('selected');
Route::get('/coordinators', 'RestController@coordinators');
Route::post('/store-club','ClubController@storeClub')->name('clubs.store-club');
Route::post('/update-club/{id}','ClubController@updateClub')->name('clubs.update-club');
Route::post('/delete-club','ClubController@deleteClub')->name('clubs.delete-club');





// Route::group(['middleware' => ['permission:groups']], function () {
    Route::resource('groups', 'GroupsController');
// });

// Route::group(['middleware' => ['permission:permissions']],function(){
    Route::resource('permissions','PermissionsController');
// });
// // Route::resource('users', 'UserController');

Route::resource('users', 'UserController');


Route::resource('clubs', 'ClubController');

Route::get('imports','ClubController@imports')->name('imports.index');
Route::post('imports','ClubController@upload')->name('imports.upload');

Route::get('export','ClubController@export')->name('export');

Route::get('/active/{id}','RestController@active')->name('active');
Route::get('/unactive/{id}','RestController@unactive')->name('unactive');

Route::get('/active-club/{id}','ClubController@active')->name('active.club');
Route::get('/unactive-club/{id}','ClubController@unactive')->name('unactive.club');
Route::post('/login-altafit','LandingController@login')->name('login.altafit');
Route::post('/password-altafit','LandingController@reset')->name('reset.altafit');
Route::get('recovery/{token}','LandingController@recovery')->name('recovery');
Route::post('logout', 'LandingController@logout')->name('logout');

resources/views/partials/card.blade.php
@foreach($clubs as $key => $club)
    <div class="card-club col-sm-12 element-input mb-3 pd-zero shadow">
        <div class="card-header @if($club->active == 0) card-inactive @endif">
            <h3>
                <label for="" class="title-card">
                    {{ $club->uuid }} - {{ $club->name }} <span class="light">|</span> <small>Razón social: {{ $club->bussines_name }}</small> <span class="light">|</span> <small>CIF: {{ $club->cif }}</small> 
                </label>

                <a 
                    class="btn btn-primary btn-header right dropdown-toggle d-flex align-items-center justify-content-center optionsDropdown" data-id="{{ $key }}" id="optionsDropdown-{{ $key }}" href="#" data-toggle="dropdown"
                    data-toggle="tooltip" data-placement="left" data-original-title="Más opciones">
                   <i class="mdi mdi-dots-horizontal"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list opts optionsDropdown-{{ $key }}" aria-labelledby="optionsDropdown-{{ $key }}">
                    <a class="dropdown-item preview-item opts-item" href="{{ route('clubs.edit',$club->id) }}">
                        <div class="preview-thumbnail opts-icon">
                            <div class="preview-icon bg-info">
                                <i class="mdi mdi-tooltip-edit mx-0"></i>
                            </div>
                        </div>
                        <div class="preview-item-content opts-content">
                            <h6 class="preview-subject font-weight-normal">Modificar</h6>
                        </div>
                    </a>

                    @if($club->active == 1)
                        <a class="dropdown-item preview-item opts-item" href="{{ route('unactive.club',$club->id) }}">
                            <div class="preview-thumbnail opts-icon">
                                <div class="preview-icon bg-info">
                                    <div class="icon-basf-small" style="background-image: url({{ asset('img/ban.png') }})"></div>
                                </div>
                            </div>
                            <div class="preview-item-content opts-content">
                                <h6 class="preview-subject font-weight-normal">Desactivar</h6>
                            </div>
                        </a>
                    @endif

                    @if($club->active == 0)
                        <a class="dropdown-item preview-item opts-item" href="{{ route('active.club',$club->id) }}">
                            <div class="preview-thumbnail opts-icon">
                                <div class="preview-icon bg-info">
                                    <div class="icon-basf-small" style="background-image: url({{ asset('img/success.png') }})"></div>
                                </div>
                            </div>
                            <div class="preview-item-content opts-content">
                                <h6 class="preview-subject font-weight-normal">Activar</h6>
                            </div>
                        </a>
                    @endif
                    
                    <a class="dropdown-item preview-item opts-item" onclick="showSwal('warning-message-and-cancel',{{ $club->id }})">
                        <div class="preview-thumbnail opts-icon">
                            <div class="preview-icon bg-info">
                                <i class="mdi mdi-close mx-0"></i>
                            </div>
                        </div>
                        <div class="preview-item-content opts-content">
                            <h6 class="preview-subject font-weight-normal">Eliminar</h6>
                        </div>
                    </a>
                </div>
            </h3>
        </div>
        <div class="card-body">
            <ul class="list-unstyled list-horizontal">
                <li>
                    <i class="mdi mdi-map-marker-radius"></i> 
                    <span>Dirección : {{ $club->address }}, {{ $club->postal_code }} </span>
                </li>
                <li>
                    <i class="mdi mdi-city"></i> 
                    <span>Ciudad : {{ $club->city }} </span>
                </li>
                <li>
                    <i class="mdi mdi-flag-checkered"></i> 
                    <span>Provincia : {{ $club->providence }} </span>
                </li>
            </ul>
            

            <ul class="list-unstyled list-horizontal">
                <li>
                    <i class="mdi mdi-account-key"></i> 
                    <span>Director : {{ $club->director }} </span>
                </li>{{-- 
                <li>
                    <i class="mdi mdi-account-multiple-outline"></i> 
                    <span>Coordinador : {{ $club->coordinator }} </span>
                </li> --}}
            </ul>
        </div>

        {{-- <div class="card-footer">
            <ul class="list-unstyled list-horizontal">
                <li>
                    <i class="mdi mdi-lock"></i> 
                    <span>Llave privada : {{ $club->pv_sk }} </span>
                </li>
                <li>
                    <i class="mdi mdi-key-variant"></i> 
                    <span>Llave pública : {{ $club->pv_pk }} </span>
                </li>
                <li>
                    <i class="mdi mdi-numeric-1-box-multiple-outline"></i> 
                    <span>ID Provis : {{ $club->provis_id }} </span>
                </li>
            </ul>
        </div> --}}
    </div>
@endforeach

resources/views/partials/table.blade.php
<div class="card">
    <div class="card-body card-table-club">
        <div class="table-responsive">
            <table class="table" id="clubs-table">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Origen</th>
                        <th>Tipo</th>
                        <th>Provincia</th>
                        <th class="text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($clubs as $key => $club)
                        <tr class="@if($club->active == 0) card-inactive @endif">
                            <td>{!! $club->uuid !!}</td>
                            <td>{!! $club->name !!}</td>
                            <td>{!! $club->origin !!}</td>
                            <td>{!! $club->type !!}</td>
                            <td>{!! $club->providence !!}</td>
                            <td class="text-center">
                                <div class='btn-group'>
                                    @if($club->active == 1)
                                        <a 
                                            href="{{ route('unactive.club',$club->id) }}"
                                            data-toggle="tooltip" title="Activar club"
                                            data-placement= 'top'
                                             class="btn btn-warning single-button btn-xs">
                                            <div class="icon-basf-small" style="background-image: url({{ asset('img/ban.png') }})"></div>
                                        </a>
                                    @endif

                                    @if($club->active == 0)
                                        <a 
                                            href="{{ route('active.club',$club->id) }}" 
                                            data-toggle="tooltip" title="Desactivar club"
                                            data-placement= 'top'
                                             class="btn btn-success single-button btn-xs">
                                            <div class="icon-basf-small" style="background-image: url({{ asset('img/success.png') }})"></div>
                                        </a>
                                        
                                    @endif
                                    {{-- @can('edit_clubs') --}}
                                        <a 
                                            data-toggle="tooltip" title="Editar grupo"
                                            data-placement= 'top'
                                            href="{!! route('clubs.edit', [$club->id]) !!}" class='btn btn-info single-button btn-xs'>
                                            <div class="icon-basf-small" style="background-image: url({{ asset('img/edit.png') }})"></div>
                                        </a>
                                    {{-- @endcan
                                    @can('delete_clubs') --}}
                                        <button 
                                            data-toggle="tooltip" title="Borrar grupo"
                                            data-placement= 'top'
                                            onclick="return confirm('Estas seguro de eliminar este recurso?')" type="submit" class="btn btn-danger single-button btn-xs">
                                            <div class="icon-basf-small" style="background-image: url({{ asset('img/trash.png') }})"></div>
                                        </button>
                                   {{--  @endcan --}}
                                </div>
                            </td>
                        </tr>
                    @endforeach
                
                </tbody>
            </table>   
        </div>
    </div>
</div>