routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login')->with('errorsLogin','');
})->name('screen');

Route::get('/login', function () {
    return view('auth.login')->with('errorsLogin','');
})->name('login');

Route::get('/reset', function () {
    return view('auth.passwords.email');
})->name('password.request');


Route::get('/home', 'HomeController@index')->name('home');
Route::post('/change-password', 'UserController@changePassword')->name('change.password');

Route::get('/cities', 'RestController@cities');
Route::get('/providences', 'RestController@providences');

Route::post('/cities', 'RestController@saveCities');
Route::post('/providences', 'RestController@saveProvidences');

Route::get('/directors', 'RestController@directors');
Route::get('/selected/{club}','RestController@selected')->name('selected');
Route::get('/coordinators', 'RestController@coordinators');
Route::post('/store-club','ClubController@storeClub')->name('clubs.store-club');
Route::post('/update-club/{id}','ClubController@updateClub')->name('clubs.update-club');
Route::post('/delete-club','ClubController@deleteClub')->name('clubs.delete-club');





// Route::group(['middleware' => ['permission:groups']], function () {
    Route::resource('groups', 'GroupsController');
// });

// Route::group(['middleware' => ['permission:permissions']],function(){
    Route::resource('permissions','PermissionsController');
// });
// // Route::resource('users', 'UserController');

Route::resource('users', 'UserController');


Route::resource('clubs', 'ClubController');

Route::get('imports','ClubController@imports')->name('imports.index');
Route::post('imports','ClubController@upload')->name('imports.upload');

Route::get('export','ClubController@export')->name('export');

Route::get('/active/{id}','RestController@active')->name('active');
Route::get('/unactive/{id}','RestController@unactive')->name('unactive');

Route::get('/active-club/{id}','ClubController@active')->name('active.club');
Route::get('/unactive-club/{id}','ClubController@unactive')->name('unactive.club');
Route::post('/login-altafit','LandingController@login')->name('login.altafit');
Route::post('/password-altafit','LandingController@reset')->name('reset.altafit');
Route::get('recovery/{token}','LandingController@recovery')->name('recovery');
Route::post('logout', 'LandingController@logout')->name('logout');

app/Http/Controllers/GroupsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateGroupsRequest;
use App\Http\Requests\UpdateGroupsRequest;
use App\Repositories\GroupsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class GroupsController extends AppBaseController
{
    /** @var  GroupsRepository */
    private $groupsRepository;

    public function __construct(GroupsRepository $groupsRepo)
    {
        $this->groupsRepository = $groupsRepo;
    }

    /**
     * Display a listing of the Groups.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->groupsRepository->pushCriteria(new RequestCriteria($request));
        $groups = $this->groupsRepository->all();

        return view('groups.index')
            ->with('groups', $groups);
    }

    /**
     * Show the form for creating a new Groups.
     *
     * @return Response
     */
    public function create()
    {
        $listPermissions = $this->groupsRepository->getListPermissions(collect([]));
      
        return view('groups.create')->with('list',$listPermissions);
    }

    /**
     * Store a newly created Groups in storage.
     *
     * @param CreateGroupsRequest $request
     *
     * @return Response
     */
    public function store(CreateGroupsRequest $request)
    {
        $input = $request->all();
        $groups = $this->groupsRepository->createGroupAndSyncPermissions($input);
      
        if($groups){
          Flash::success('Grupo creado correctamente.');
        }else{
          Flash::error('Ocurrio un error contacta al administrador.');
        }
        
        return redirect(route('groups.index'));
    }

    /**
     * Display the specified Groups.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $groups = $this->groupsRepository->findWithoutFail($id);
        $listPermissions = $this->groupsRepository->getListPermissions($groups->permissions);
        
        if (empty($groups)) {
            Flash::error('Grupo no encontrado');

            return redirect(route('groups.index'));
        }

        return view('groups.show')->with('groups', $groups)->with('list',$listPermissions);
    }

    /**
     * Show the form for editing the specified Groups.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $groups = $this->groupsRepository->findWithoutFail($id);
        $listPermissions = $this->groupsRepository->getListPermissions(collect([]));
      
        if (empty($groups)) {
            Flash::error('Grupo no encontrado');
            return redirect(route('groups.index'));
        }

        
      
        return view('groups.edit')->with('groups', $groups)->with('list',$listPermissions);
    }

    /**
     * Update the specified Groups in storage.
     *
     * @param  int              $id
     * @param UpdateGroupsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateGroupsRequest $request)
    {
        $groups = $this->groupsRepository->findWithoutFail($id);

        if (empty($groups)) {
            Flash::error('Grupo no encontrado');

            return redirect(route('groups.index'));
        }

        $groups = $this->groupsRepository->updateGroupAndSyncPermissions($request->all(), $id);
  
        if($groups){
          Flash::success('Grupo editado correctamente.');
        }else{
          Flash::error('Ocurrio un error contacta al administrador.');
        }
        
        return redirect(route('groups.index'));
    }

    /**
     * Remove the specified Groups from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $groups = $this->groupsRepository->findWithoutFail($id);

        if (empty($groups)) {
           Flash::error('Grupo no encontrado');
            return redirect(route('groups.index'));
        }

        $this->groupsRepository->delete($id);

        Flash::success('Grupo eliminado correctamente.');

        return redirect(route('groups.index'));
    }
}

resources/views/groups/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Crear grupo') }}</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-warning alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-warning"></i> Cuidado!</h4>
                                Debe verificar los siguientes errores antes de continuar:
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        {!! Form::open(['route' => 'groups.store']) !!}

                            @include('groups.fields')

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/groups/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Editar grupo') }}</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-warning alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-warning"></i> Cuidado!</h4>
                                Debe verificar los siguientes errores antes de continuar:
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        
                        {!! Form::model($groups, ['route' => ['groups.update', $groups->id], 'method' => 'patch']) !!}

                            @include('groups.fields_edit')

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/groups/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>


@foreach($list as $key => $item)
  <div class="col-sm-4 container-panel-permission">
    <h3>{{$key}}</h3>
    <div class="well">
        <ul class="list-unstyled">
          @foreach($item as $value)
            <li class="list-group-item">
                <div class="form-check">
                  <label class="form-check-label">
                    {!! Form::checkbox('permissions[]', remove_keyword($value.'_'.$key), ['class' => 'form-check-input']) !!} 
                    {{translate_keywords($value)}}
                  </label>
                </div>
            </li>
           @endforeach
        </ul>
    </div>
 </div>
@endforeach




<!-- Submit Field -->
<div class="form-group col-sm-12 container-buttons pd-zero">
    {!! Form::submit('Guardar', ['class' => 'right single-button  btn btn-primary']) !!}
    <a href="{!! route('groups.index') !!}" class="right single-button  btn btn-default">Cancelar</a>
</div>

resources/views/groups/fields_edit.blade.php
<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>


@foreach($list as $key => $item)
  <div class="col-sm-4 container-panel-permission">
    <h3>{{$key}}</h3>
    <div class="well">
        <ul class="list-unstyled">
          @foreach($item as $value)
            <li class="list-group-item">
                <div class="form-check">
                  <label class="form-check-label">
                    {!! Form::checkbox('permissions[]', remove_keyword($value.'_'.$key), $groups->hasPermissionTo(remove_keyword($value.'_'.$key)),['class' => 'form-check-input']) !!} 
                    {{translate_keywords($value)}}
                  </label>
                </div>
            </li>
           @endforeach
        </ul>
    </div>
 </div>
@endforeach




<!-- Submit Field -->
<div class="form-group col-sm-12 container-buttons pd-zero">
    {!! Form::submit('Guardar', ['class' => 'right single-button  btn btn-primary']) !!}
    <a href="{!! route('groups.index') !!}" class="right single-button  btn btn-default">Cancelar</a>
</div>

resources/views/groups/index.blade.php
@extends('layouts.app')

@section('content')
   <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('flash::message')
                <div class="card">
                    <div class="card-header">
                        <h3>
                            {{ __('Listado de grupos') }}
                            @can('create_groups')
                                <a 
                                    data-toggle="tooltip" title="Crear grupo"
                                    data-placement= 'top'
                                    class="btn btn-primary right single-button btn-xs first-button"  href="{!! route('groups.create') !!}">
                                    <div class="icon-basf" style="background-image: url({{ asset('img/team.png') }})"></div>
                                </a>
                            @endcan
                            @can('view_permissions')
                                <a 
                                    data-toggle="tooltip" title="Listado de permisos"
                                    data-placement= 'top'
                                    class="btn btn-primary right single-button btn-xs"  href="{!! route('permissions.index')  !!}">
                                    <div class="icon-basf" style="background-image: url({{ asset('img/permission.png') }})"></div>
                                </a>
                            @endcan
                        </h3>
                    </div>

                    <div class="card-body">
                        @include('groups.table')
                    </div>

                    <div class="card-footer">
                        <div class="text-center">
        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/groups/show.blade.php
@extends('layouts.admin')

@section('content')
    <section class="content-header">
        <h1>
            Groups
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('groups.show_fields')
                    <div class="col-sm-12">
                      <a href="{!! route('groups.index') !!}" class="btn btn-default pull-right">Regresar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/groups/show_fields.blade.php
<div class="col-sm-12 table-responsive">
 	<table class="table table-bordered table-condensed table-striped ">
	<thead>
		<tr>
		  <th>Titulo</th>
		  <th>Valor</th>
		</tr>
	</thead>
	<tbody>
		<!-- Id Field -->
		<tr>
		  <td>
    		     {!! Form::label('id', 'Id:') !!}
		  </td>
		  <td>
		      <p>{!! $groups->id !!}</p>
		  </td>
		</tr>
		<!-- Name Field -->
		<tr>
		  <td>
   		       {!! Form::label('name', 'Nombre:') !!}
    		  </td>
		  <td>
		       <p>{!! $groups->name !!}</p>
		  </td>
		</tr>

		<!-- Created At Field -->
		<tr>
	 	   <td>
    		        {!! Form::label('created_at', 'Fecha de creacion:') !!}
   		   </td>
		   <td>
		        <p>{!! $groups->created_at !!}</p>
		   </td>
		</tr>
	  </tbody>
	</table>
</div>

<div class="col-sm-12">
	<h2>Listado de permisos asignados</h2>
	@foreach($list as $key => $item)
		<div class="col-xs-4">
			<h3>{{$key}}</h3>
			<div class="well">
					<ul class="list-unstyled">
						@foreach($item as $value)
							<li class="list-group-item">
									 {{translate_keywords($value)}}
							</li>
						 @endforeach
					</ul>
			</div>
	 </div>
	@endforeach
</div>

resources/views/groups/table.blade.php
<div class="table-responsive">
    <table class="table" id="groups-table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            @if($groups->isEmpty())
                <tr>
                    <td colspan="5" class="text-center">No hay registros</td>
                </tr>
            @else
                @foreach($groups as $groups)
                    <tr>
                        <td>{!! $groups->name !!}</td>
                        <td class="right-text">
                            {!! Form::open(['route' => ['groups.destroy', $groups->id], 'method' => 'delete' , 'class' => 'form-buttons']) !!}
                            <div class='btn-group'>
                                {{-- @can('view_groups')
                                    <a href="{!! route('groups.show', [$groups->id]) !!}" class='btn btn-default btn-xs'>
                                        <i class="glyphicon glyphicon-eye-open"></i>
                                    </a>
                                @endcan --}}
                                @can('edit_groups')
                                    <a 
                                        data-toggle="tooltip" title="Editar grupo"
                                        data-placement= 'top'
                                        href="{!! route('groups.edit', [$groups->id]) !!}" class='btn btn-info single-button btn-xs'>
                                        <div class="icon-basf-small" style="background-image: url({{ asset('img/edit.png') }})"></div>
                                    </a>
                                @endcan
                                @can('delete_groups')
                                    <button 
                                        data-toggle="tooltip" title="Borrar grupo"
                                        data-placement= 'top'
                                        onclick="return confirm('Estas seguro de eliminar este recurso?')" type="submit" class="btn btn-danger single-button btn-xs">
                                        <div class="icon-basf-small" style="background-image: url({{ asset('img/trash.png') }})"></div>
                                    </button>
                                @endcan
                            </div>
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            @endif
        
        </tbody>
    </table>   
</div>